/* THE CANCEL IS COMING — data: relics, enemies, bosses, districts.
   Relic icons are [config, layer, file name] (optional 4th entry "gray" desaturates);
   they are cropped to the trait's own bounds at load time, and worn by the player.
   rar: common | rare | legendary | cursed (black market).  set: synergy ids from SETS. */
const DISTRICTS = [
  { name:"MILADY MAKER", color:"#c54e71", rule:"chests offer 4 relics" },
  { name:"REMILIO",      color:"#7db8ff", rule:"fights pay +50% $CULT" },
  { name:"BONKLER",      color:"#a6ff5e", rule:"shops are 20% cheaper" },
  { name:"CULT",         color:"#ffd75e", rule:"shrines win 65% of flips" },
];

/* Starting classes, after the Milady style tribes. relic = what you start holding; stat = flat bonuses. */
const TRIBES = [
 {id:"hypebeast", name:"HYPEBEAST", icon:"👟", relic:"chrome_hearts",  desc:"+6% crit chance",        stat:{crit:6}},
 {id:"gyaru",     name:"GYARU",     icon:"💅", relic:"silver_coin",    desc:"+60 starting $CULT",     cult:60},
 {id:"lolita",    name:"LOLITA",    icon:"🎀", relic:"strawberry",     desc:"+10 max HP",             stat:{maxhp:10}},
 {id:"harajuku",  name:"HARAJUKU",  icon:"🌈", relic:"cobain_glasses", desc:"+1 SPD",                 stat:{spd:1}},
 {id:"prep",      name:"PREP",      icon:"🎓", relic:"knife",          desc:"+1 ATK, +1 ARM",         stat:{atk:1, arm:1}},
];
/* Heat: optional difficulty, one level unlocked per win. Level n applies the first n lines. */
const HEAT = [
 "enemies have +15% HP",
 "shops cost 25% more",
 "nights are 3 moves longer and one more FUD demon hunts",
 "bosses have +20% HP and ATK",
 "one fewer relic slot",
];

const RELICS = [
 {id:"wartime_pfp", name:"Wartime PFP", rar:"rare", set:["cult"], desc:"Survive lethal damage once per fight.", icon:["Remilio", "Face", "War"], tags:[]},
 {id:"ss_drip", name:"SS Drip", rar:"rare", set:["hype"], desc:"+50% ATK.", icon:["Milady", "Shirt", "Gold Spray Puffer"], tags:[]},
 {id:"bonkler", name:"Bonkler", rar:"rare", set:["bonkler", "squad"], desc:"15%: enemy hits itself instead.", icon:["Bonkler", "Body", "Burger Bonkler Laser"], tags:[]},
 {id:"remilio_friend", name:"Remilio Friend", rar:"common", set:["squad"], desc:"Companion: strikes for 5 every 3rd tick.", icon:["Remilio", "Friend", "Bear"], tags:[]},
 {id:"eth_necklace", name:"ETH Necklace", rar:"common", set:["degen"], desc:"+50% $CULT from victories.", icon:["Milady", "Necklaces", "ETH Necklace"], tags:[]},
 {id:"cobain_glasses", name:"Cobain Glasses", rar:"common", set:["schizo"], desc:"+12% dodge chance.", icon:["Milady", "Glasses", "Cobain Glasses"], tags:[]},
 {id:"hat_911", name:"911 Hat", rar:"common", set:["hype"], desc:"+3 SPD.", icon:["Remilio", "Hat", "911 Hat"], tags:[]},
 {id:"ak47", name:"AK47", rar:"common", set:["armed"], desc:"+9 ATK, -2 SPD.", icon:["Remilio", "Weapon", "AK47 Gold", "gray"], tags:[]},
 {id:"balenciaga_bat", name:"Balenciaga Bat", rar:"common", set:["hype"], desc:"+5 ATK, 12% stun on hit.", icon:["Remilio", "Glasses", "Balenciaga Bat"], tags:[]},
 {id:"diamond_stud", name:"Diamond Stud", rar:"common", set:["kawaii"], desc:"+25 max HP.", icon:["Milady", "Earrings", "Diamond Stud"], tags:[]},
 {id:"beetleposting", name:"Beetleposting", rar:"common", set:["schizo"], desc:"Enemies deal -20% damage.", icon:["Remilio", "Glasses", "Clout Goggles"], tags:[]},
 {id:"drip_score", name:"Drip Score", rar:"common", set:["hype"], desc:"+2 ATK per relic equipped.", icon:["Milady", "Shirt", "Bosozuku Jacket"], tags:[]},
 {id:"cult_robe", name:"Cult Robe", rar:"rare", set:["cult"], desc:"Heal 2 HP every tick.", icon:["Remilio", "Costume", "Nun"], tags:[]},
 {id:"gucci_cone", name:"Gucci Cone", rar:"common", set:["hype"], desc:"+20% crit chance.", icon:["Milady", "Hat", "Fez"], tags:[]},
 {id:"snakebites", name:"Snakebites", rar:"common", set:["schizo"], desc:"Hits poison: 2 dmg/tick for 3 ticks.", icon:["Milady", "Face Decoration", "Snakebites"], tags:[]},
 {id:"blunt", name:"Blunt", rar:"rare", set:["schizo"], desc:"First hit each fight deals 3x.", icon:["Remilio", "Mouth", "Cigar"], tags:[]},
 {id:"bfg", name:"BFG9000", rar:"rare", set:["armed"], desc:"+15 ATK, -15 max HP.", icon:["Remilio", "Weapon", "BFG9000"], tags:[]},
 {id:"birthday_hat", name:"Birthday Hat", rar:"common", set:["kawaii"], desc:"Heal 15 HP on kill.", icon:["Milady", "Hat", "Cake Hat"], tags:[]},
 {id:"bulletproof", name:"Bulletproof", rar:"common", set:["bonkler"], desc:"+6 ARM.", icon:["Remilio", "Hat", "Viking"], tags:[]},
 {id:"blood_splatter", name:"Blood Splatter", rar:"common", set:["schizo"], desc:"+5 ATK while below half HP.", icon:["Remilio", "Face", "Scar"], tags:[]},
 {id:"frog_costume", name:"Frog Costume", rar:"common", set:["kawaii"], desc:"+30 max HP, -1 SPD.", icon:["Remilio", "Costume", "Frog"], tags:[]},
 {id:"network_spirituality", name:"Network Spirituality", rar:"rare", set:["cult"], desc:"Start each fight with a 12 HP shield.", icon:["Milady", "Hat", "Halo"], tags:[]},
 {id:"post_authorship", name:"Post-Authorship", rar:"common", set:["cult"], desc:"Plagiarism as praxis: +1 ATK per kill this run (max +10).", icon:["Milady", "Shirt", "Remilia Tank"], tags:[]},
 {id:"vibe_shift", name:"Vibe Shift", rar:"rare", set:["schizo"], desc:"Enemies start every fight stunned.", icon:["Remilio", "Glasses", "Shutter Shades"], tags:[]},
 {id:"cancelversary", name:"Cancelversary", rar:"rare", set:["kawaii"], desc:"+4 ATK for every boss you have beaten.", icon:["Milady", "Hat", "Pink Bow"], tags:[]},
 {id:"swag_score", name:"Swag Score", rar:"common", set:["hype"], desc:"+3% crit chance per relic equipped.", icon:["Remilio", "Shirt", "Supreme Fox Jersey"], tags:[]},
 {id:"tinfoil", name:"Tinfoil Hat", rar:"rare", set:["schizo"], desc:"FUD can't suppress your relics. RATIO'D only deals 2.", icon:["Remilio", "Hat", "Tinfoil"], tags:[]},
 {id:"hodl", name:"HODL", rar:"common", set:["degen"], desc:"Take 30% less damage while below half HP.", icon:["Remilio", "Hat", "HODL"], tags:[]},
 {id:"no_meme", name:"There Is No Meme", rar:"rare", set:["degen", "kawaii"], desc:"I love you. 20%: a victory pays triple $CULT.", icon:["Milady", "Eyes", "Heart"], tags:[]},
 {id:"reserve", name:"Bonkler Reserve", rar:"rare", set:["bonkler"], desc:"Burn to redeem: lethal damage destroys this relic and heals you to full.", icon:["Bonkler", "Offhand", "Remilia Crest"], tags:[]},
 {id:"harajuku", name:"Harajuku Dye", rar:"common", set:["kawaii"], desc:"+10 max HP, +1 SPD.", icon:["Milady", "Hair", "Bowl Harajuku Dye"], tags:[]},
 {id:"maid", name:"Maid Outfit", rar:"common", set:["kawaii"], desc:"Heal 6 HP after every victory.", icon:["Milady", "Shirt", "Maid"], tags:[]},
 {id:"hypebeast", name:"Stone Island", rar:"common", set:["hype"], desc:"+4 ARM. Shops cost 15% more.", icon:["Remilio", "Shirt", "Stone Island Puffer"], tags:[]},
 {id:"katana", name:"Katana", rar:"common", set:["armed"], desc:"+4 ATK, +10% crit chance.", icon:["Remilio", "Weapon", "Katana"], tags:[]},
 {id:"energy_sword", name:"Energy Sword", rar:"rare", set:["armed", "bonkler"], desc:"Your hits ignore enemy ARM.", icon:["Bonkler", "Hand", "Energy Sword"], tags:[]},
 {id:"mexican_coke", name:"Mexican Coke", rar:"common", set:["bonkler"], desc:"+2 SPD, +10 max HP.", icon:["Bonkler", "Hand", "Mexican Coke"], tags:[]},
 {id:"airpods", name:"Airpods", rar:"common", set:["hype"], desc:"Can't hear the FUD: enemies never crit you.", icon:["Remilio", "Earrings", "Airpod Pro"], tags:[]},
 {id:"remilionaire", name:"#REMILIONAIRE", rar:"rare", set:["degen"], desc:"Elites and bosses pay double $CULT.", icon:["Remilio", "Shirt", "Money Gang"], tags:[]},
 {id:"golden_axe", name:"Golden Axe", rar:"rare", set:["armed", "bonkler"], desc:"+6 ATK. Your crits stun.", icon:["Bonkler", "Hand", "Golden Axe"], tags:[]},
 {id:"knife", name:"Knife", rar:"common", set:["armed", "bonkler"], desc:"+3 ATK, +2 SPD.", icon:["Bonkler", "Hand", "Knife"], tags:[]},
 {id:"wwe_belt", name:"Champion Belt", rar:"legendary", set:["armed"], desc:"+4 ATK for every ARMED relic you hold.", icon:["Remilio", "Shirt", "WWE Champion Belt"], tags:[]},
 {id:"chrome_hearts", name:"Chrome Hearts", rar:"common", set:["hype"], desc:"+1 ATK, +8% crit chance.", icon:["Remilio", "Earrings", "Chrome Hearts"], tags:[]},
 {id:"yakuza_suit", name:"Yakuza Suit", rar:"rare", set:["hype", "cheese"], desc:"+3 ATK, +3 ARM.", icon:["Remilio", "Shirt", "Yakuza Suit"], tags:[]},
 {id:"mape_hoodie", name:"Mape Hoodie", rar:"common", set:["hype"], desc:"+12 max HP, +5% crit chance.", icon:["Milady", "Shirt", "Mape Hoodie"], tags:[]},
 {id:"trucker", name:"White Rabbit Trucker", rar:"legendary", set:["hype"], desc:"Your crits heal you for 5.", icon:["Milady", "Hat", "Trucker White Rabbit"], tags:[]},
 {id:"scarface", name:"Scarface Suit", rar:"rare", set:["degen", "cheese"], desc:"+1 damage per 40 $CULT you hold (max +8).", icon:["Remilio", "Shirt", "Scarface Suit"], tags:[]},
 {id:"silver_coin", name:"Silver Coin", rar:"common", set:["degen"], desc:"+15 $CULT after every victory.", icon:["Milady", "Necklaces", "Silver Coin Necklace"], tags:[]},
 {id:"game_watch", name:"Game & Watch", rar:"legendary", set:["degen", "bonkler"], desc:"Degen Shrines never lose.", icon:["Bonkler", "Offhand", "Game & Watch"], tags:[]},
 {id:"cat_ears", name:"Cat Ears", rar:"common", set:["kawaii"], desc:"+6% dodge. Heal 3 HP whenever you dodge.", icon:["Milady", "Hat", "Cat Ears with Bell"], tags:[]},
 {id:"strawberry", name:"Strawberry Earring", rar:"common", set:["kawaii"], desc:"+8 max HP. Heal 3 HP after every victory.", icon:["Milady", "Earrings", "Strawberry Earring"], tags:[]},
 {id:"lollipop", name:"Lollipop", rar:"common", set:["kawaii"], desc:"Heal 1 HP every tick.", icon:["Remilio", "Mouth", "Lollipop"], tags:[]},
 {id:"heart_tattoo", name:"Star Heart Tattoo", rar:"legendary", set:["kawaii"], desc:"All your healing is doubled.", icon:["Milady", "Face Decoration", "Star Heart Tattoo"], tags:[]},
 {id:"jesus_tank", name:"Jesus Tank", rar:"common", set:["cult"], desc:"Start each fight with an 8 HP shield.", icon:["Milady", "Shirt", "Jesus Tank"], tags:[]},
 {id:"evil_eye", name:"Evil Eye", rar:"rare", set:["cult"], desc:"Reflect 2 damage whenever you are hit.", icon:["Milady", "Necklaces", "Evil Eye Necklace"], tags:[]},
 {id:"matrix", name:"Matrix Shades", rar:"rare", set:["schizo"], desc:"+12% dodge. After a dodge, your next hit crits.", icon:["Remilio", "Glasses", "Matrix"], tags:[]},
 {id:"fbi_cap", name:"FBI Cap", rar:"common", set:["schizo"], desc:"Every enemy hit deals 2 less.", icon:["Remilio", "Hat", "FBI Cap"], tags:[]},
 {id:"milady_pilled", name:"Milady Pilled", rar:"legendary", set:["schizo"], desc:"Your poison deals triple damage.", icon:["Milady", "Face Decoration", "Milady Pilled Tattoo"], tags:[]},
 {id:"tails", name:"Tails", rar:"common", set:["squad"], desc:"Companion: 30% each tick to hit for 4.", icon:["Remilio", "Friend", "Tails"], tags:[]},
 {id:"hobbes", name:"Hobbes", rar:"rare", set:["squad"], desc:"Companion: blocks the first hit of every fight.", icon:["Remilio", "Friend", "Hobbes"], tags:[]},
 {id:"gold_sonic", name:"Gold Sonic", rar:"legendary", set:["squad"], desc:"Your companions act twice.", icon:["Remilio", "Friend", "Gold Sonic"], tags:[]},
 {id:"pikachu", name:"Pikachu Suit", rar:"rare", set:["squad"], desc:"Every 4th tick: shock for 8, ignoring ARM.", icon:["Remilio", "Costume", "Pikachu"], tags:[]},
 {id:"cookie", name:"Cookie", rar:"common", set:["bonkler"], desc:"Heal 10 HP at the start of every fight.", icon:["Bonkler", "Offhand", "Cookie"], tags:[]},
 {id:"shark_suit", name:"Shark Suit", rar:"rare", set:["cheese"], desc:"+4 ATK, +10 max HP.", icon:["Remilio", "Costume", "Shark"], tags:[]},
 {id:"cigarette", name:"Kumicho's Cigarette", rar:"common", set:["cheese"], desc:"Your crits deal +4 damage.", icon:["Remilio", "Mouth", "Cigarette"], tags:[]},
 {id:"dino", name:"Dino Enforcer", rar:"common", set:["cheese", "squad"], desc:"Companion: bites for 3 every other tick.", icon:["Remilio", "Friend", "Dino"], tags:[]},
 {id:"blockhead", name:"Blockhead", rar:"common", set:["bonkler"], desc:"Minimum viable metaverse: +2 ARM, +8 max HP.", icon:["Bonkler", "Head", "Lego Head"], tags:[]},
 {id:"webring", name:"Radbro Webring", rar:"legendary", set:[], desc:"A reflection of a reflection: counts as one more relic toward every set you already hold.", icon:["Milady", "Glasses", "Sunglasses"], tags:[]},
 {id:"memcard", name:"Memory Card", rar:"rare", set:["bonkler"], desc:"MiladyStation save state: once per run, lethal damage reloads you at half HP.", icon:["Bonkler", "Head", "PlayStation Vita"], tags:[]},
 {id:"custom", name:"Oh... I See", rar:"legendary", set:["kawaii"], desc:"A hand-drawn 1/1 by Shiro: +3 ATK, +2 ARM, +1 SPD, +10 max HP.", icon:["Remilio", "Hat", "Halo"], tags:[]},
 {id:"lain", name:"Lain", rar:"cursed", set:["schizo"], desc:"25% dodge chance.", icon:["Remilio", "Background", "Lain Room"], tags:["blackmarket"]},
 {id:"amogus", name:"Amogus", rar:"cursed", set:["squad"], desc:"Companion: 20% chance to one-shot non-bosses.", icon:["Remilio", "Friend", "Amogus"], tags:["blackmarket"]},
 {id:"gold_ak", name:"Gold AK47", rar:"cursed", set:["armed"], desc:"+13 ATK.", icon:["Remilio", "Weapon", "AK47 Gold"], tags:["blackmarket"]},
 {id:"moteiga", name:"Mottega Shades", rar:"cursed", set:["hype"], desc:"+4 ARM, +10% dodge.", icon:["Milady", "Glasses", "Mottega Sunglasses Blue"], tags:["blackmarket"]},
 {id:"crown", name:"Burger Crown", rar:"cursed", set:["degen"], desc:"+100% $CULT from victories.", icon:["Remilio", "Hat", "Burger King Crown"], tags:["blackmarket"]},
 {id:"platinum", name:"Amex Platinum", rar:"cursed", set:["degen"], desc:"Shops cost 30% less.", icon:["Remilio", "Weapon", "Money Phone"], tags:["blackmarket"]},
];

/* Synergies: hold enough relics of a set (relic.set) and its tiers switch on. tiers: [count, effect]. */
const SETS = [
 {id:"armed",   name:"ARMED",     icon:"⚔️", color:"#ff8a5c", tiers:[[2,"+4 ATK"],[3,"every 3rd swing strikes twice"]]},
 {id:"hype",    name:"HYPEBEAST", icon:"👟", color:"#ffd75e", tiers:[[2,"+10% crit chance"],[4,"crits deal triple damage"]]},
 {id:"degen",   name:"DEGEN",     icon:"🎰", color:"#a6ff5e", tiers:[[2,"+30% $CULT from victories"],[3,"shops cost 25% less"]]},
 {id:"kawaii",  name:"KAWAII",    icon:"🎀", color:"#ff9ecb", tiers:[[2,"+12 max HP"],[4,"heal 2 HP every tick"]]},
 {id:"cult",    name:"CULT",      icon:"🕯️", color:"#f3e3b5", tiers:[[2,"+8 shield at fight start"],[3,"+4 shield every 4th tick"]]},
 {id:"schizo",  name:"SCHIZO",    icon:"📡", color:"#b9a4ff", tiers:[[2,"+10% dodge"],[4,"dodges strike back for your ATK"]]},
 {id:"squad",   name:"SQUAD",     icon:"🧸", color:"#8fd6ff", tiers:[[2,"companions deal +3"],[3,"companion hits heal you 2"]]},
 {id:"bonkler", name:"BONKLER",   icon:"🤖", color:"#7dffb0", tiers:[[2,"+3 ARM"],[4,"25% chance to strike twice"]]},
 {id:"cheese",  name:"CHEESEWORLD", icon:"🧀", color:"#ffb52e", tiers:[[2,"they go hard: +1 ATK every 3rd tick · deep fried"],[3,"cheese is money: +3 $CULT per hit you land"]]},
];
/* draft odds per rarity, and what a shop charges for one */
const RARITY = { common:{w:10, price:60}, rare:{w:4, price:100}, legendary:{w:1.2, price:170}, cursed:{w:3, price:120} };

/* tier: mon | elite | hunter. home: district indexes it spawns in (the CULT district spawns anything).
   trait "mirror" copies part of your ATK, "thief" steals $CULT on hit (kill it to get it back),
   "hard" gains ATK every 3rd tick, "creeper" blows up when it dies, "bomber" bombs you every 4th tick, "revive" gets back up once at half HP.
   fx "fried" = CHEESEWORLD deep-fry with a caption, "blocky" = MILADYCRAFT blocks, "schizo" = SCHIZOPOSTERS
   text overlay, "ps1" = MILADYSTATION low-poly dither, "pixel" = PIXELADY, "undead" = Pixelady WOTLK Death Knight. picks pin trait layers. */
const ENEMIES = [
 {id:"grunt", name:"Remilio Grunt", cfg:"Remilio", tier:"mon", home:[1], hp:22, atk:5, arm:0, spd:4, lck:5, cult:[20,35]},
 {id:"reply", name:"Reply Guy", cfg:"Remilio", tier:"mon", home:[1], hp:18, atk:5, arm:0, spd:8, lck:5, cult:[20,35]},
 {id:"poster", name:"Milady Poster", cfg:"Milady", tier:"mon", home:[0], hp:20, atk:6, arm:0, spd:6, lck:12, cult:[20,35]},
 {id:"deriv", name:"Derivative", cfg:"Milady", tier:"mon", home:[0], trait:"mirror", hp:26, atk:4, arm:0, spd:4, lck:5, cult:[25,40]},
 {id:"sniper", name:"Auction Sniper", cfg:"Bonkler", tier:"mon", home:[2], hp:24, atk:6, arm:1, spd:3, lck:25, cult:[25,40]},
 {id:"paper", name:"Paper Hands", cfg:"Bonkler", tier:"mon", home:[2], hp:16, atk:6, arm:0, spd:9, lck:5, cult:[30,50]},
 {id:"bagholder", name:"Carpetbagger", cfg:"Remilio", tier:"elite", home:[1], hp:30, atk:12, arm:0, spd:7, lck:15, cult:[50,80]},
 {id:"elite", name:"Remilio Elite", cfg:"Remilio", tier:"elite", home:[1], hp:42, atk:8, arm:1, spd:5, lck:8, cult:[45,70]},
 {id:"journo", name:"Journo", cfg:"Milady", tier:"elite", home:[0], hp:40, atk:9, arm:1, spd:6, lck:10, cult:[50,75]},
 {id:"pixelady", name:"Pixelady", cfg:"Milady", tier:"mon", home:[0], fx:"pixel", hp:21, atk:6, arm:0, spd:6, lck:10, cult:[20,35]},
 {id:"dk", name:"Death Knight", cfg:"Milady", tier:"elite", home:[0,2], trait:"revive", fx:"undead", hp:28, atk:8, arm:2, spd:4, lck:8, cult:[60,90]},
 {id:"radbro", name:"Radbro", cfg:"Remilio", tier:"mon", home:[1], trait:"mirror", picks:{Glasses:"Clout Goggles"}, hp:24, atk:4, arm:0, spd:5, lck:8, cult:[25,40]},
 {id:"station", name:"Player Character", cfg:"Milady", tier:"mon", home:[0,1], fx:"ps1", hp:24, atk:5, arm:2, spd:4, lck:5, cult:[25,40]},
 {id:"schizo", name:"Schizoposter", cfg:"Milady", tier:"elite", home:[0], fx:"schizo", hp:32, atk:9, arm:0, spd:8, lck:30, cult:[50,75]},
 {id:"bonk", name:"Wild Bonkler", cfg:"Bonkler", tier:"elite", home:[2], hp:58, atk:10, arm:2, spd:3, lck:10, cult:[70,110]},
 {id:"rugdev", name:"Rug Dev", cfg:"Bonkler", tier:"elite", home:[2], trait:"thief", hp:46, atk:8, arm:2, spd:5, lck:8, cult:[60,90]},
 {id:"goon", name:"Cheddar Goon", cfg:"Remilio", tier:"mon", home:[1,2], trait:"hard", fx:"fried", caption:"THEY GO HARD",
  picks:{Costume:"Frog", Shirt:"Yakuza Suit", Mouth:"Cigarette"}, hp:22, atk:4, arm:0, spd:5, lck:8, cult:[30,45]},
 {id:"kumicho", name:"Shark Kumicho", cfg:"Remilio", tier:"elite", home:[1,2], trait:"hard", fx:"fried", caption:"BIG CHEESE",
  picks:{Costume:"Shark", Shirt:"Scarface Suit", Mouth:"Cigar"}, hp:44, atk:7, arm:1, spd:5, lck:10, cult:[80,120]},
 {id:"griefer", name:"Griefer", cfg:"Milady", tier:"mon", home:[0,2], trait:"creeper", fx:"blocky", hp:18, atk:6, arm:0, spd:7, lck:5, cult:[20,35]},
 {id:"bomber", name:"Blimp Bomber", cfg:"Milady", tier:"elite", home:[0], trait:"bomber", fx:"blocky", hp:36, atk:6, arm:1, spd:4, lck:8, cult:[55,85]},
 {id:"fud", name:"FUD Demon", cfg:"Bonkler", tier:"hunter", home:[], hp:26, atk:6, arm:0, spd:6, lck:10, cult:[40,60]},
];

/* slot: 0 = day 3, 1 = day 6, 2 = day 9. Each run draws one boss per slot. */
const BOSSES = [
 { id:"lawsuit", slot:0, name:"THE LAWSUIT", cfg:"Bonkler",
   picks:{BG:"Bonkler St", Body:"Suit", Head:"GameCube", Face:"Deal With It", Offhand:"FBI Badge"},
   hp:54, atk:6, arm:1, spd:4, lck:8, cult:[120,160],
   intro:"You have been served.",
   mechanic:"INJUNCTION: your first two relics are frozen for the whole fight.",
   flavor:"early" },
 { id:"drain", slot:1, name:"THE TREASURY DRAIN", cfg:"Bonkler",
   picks:{BG:"Aquarium", Body:"Vending Machine", Head:"PlayStation Vita", Face:"Grin", Hand:"Knife"},
   hp:96, atk:8, arm:2, spd:5, lck:10, cult:[200,260],
   intro:"A dev has the keys. The keys are gone.",
   mechanic:"DRAIN: steals 15 $CULT every tick and hits harder for it. Kill it to get it back.",
   flavor:"mid" },
 { id:"shift", slot:1, name:"THE VIBE SHIFT", cfg:"Bonkler",
   picks:{BG:"Milady World", Body:"Rilakkuma", Head:"Strawberry Hat", Face:"Star Struck"},
   hp:100, atk:8, arm:2, spd:6, lck:10, cult:[200,260],
   intro:"Everything you built your brand on is over.",
   mechanic:"SHIFT: every 4th tick, your ATK and its ATK trade places.",
   flavor:"mid" },
 { id:"allegations", slot:0, name:"THE ALLEGATIONS", cfg:"Bonkler",
   picks:{BG:"Dungeon", Body:"Suit", Head:"iDog", Face:"Evil", Offhand:"FBI Badge"},
   hp:52, atk:6, arm:1, spd:5, lck:8, cult:[120,160],
   intro:"They're saying things about you on the timeline.",
   mechanic:"FUD: each tick, 25% chance one of your relics is suppressed.",
   flavor:"day 3" },
 { id:"bonkler911", slot:1, name:"BONKLER 9/11", cfg:"Bonkler",
   picks:{BG:"Sunset", Body:"Burger Bonkler Laser", Head:"Flame Emoji", Face:">_<", Hand:"Golden Axe"},
   hp:102, atk:9, arm:2, spd:4, lck:10, cult:[200,260],
   intro:"Something terrible happened to the timeline.",
   mechanic:"CHAOS: both sides' ATK is randomized ±50% every tick.",
   flavor:"day 6" },
 { id:"cancel", slot:2, name:"THE CANCEL", cfg:"Bonkler",
   picks:{BG:"The Moon Zone", Body:"Sony PVM", Armor:"Terminator", Head:"Lego Head", Face:"T_T", Hand:"Energy Sword"},
   hp:160, atk:12, arm:3, spd:6, lck:12, cult:[400,500],
   intro:"IT IS HERE.",
   mechanic:"Cancels one of your relics at fight start. Every 5 ticks: RATIO'D for 5 pure damage.",
   flavor:"day 9 — the big bad" },
];

const NAMES = ["milady sonora","charlotte","ruri","yayo","sismo","miyako","lilith","suki",
  "beatrice","ophelia","junko","aiko","mei","hina","sakura","rin","nene","momo",
  "remilia","reisen","kagami","pixelady","lolita","gyaru","harajuku","prep","hypebeast","milady 9286"];

/* Map events. Each choice: fx list applied on success; with odds, `bad` is applied on failure.
   cost = $CULT paid up front; need:"relic" requires holding one, need:"<set id>" a relic of that set.
   fx: cult n | cultpct n | hp n | maxhp n | atk n | spd n | atkboss | moves n | relic [luck] | burn n | reveal | fight id | seed | give relicId | ps1 */
const EVENTS = [
 { id:"rave", name:"MILADY RAVE", icon:"🪩", text:"A basement in London. The bass is doing something to the timeline.",
   choices:[ {label:"dance till dawn", hint:"heal 25 HP, lose 3 moves", fx:[["hp",25],["moves",-3]]},
             {label:"work the room", hint:"50%: +60 $CULT · 50%: take 8 damage", odds:0.5, fx:[["cult",60]], bad:[["hp",-8]]} ] },
 { id:"chan", name:"MILADYCHAN", icon:"🧵", text:"An anonymous thread is talking about you.",
   choices:[ {label:"post through it", hint:"60%: +1 ATK forever · 40%: flamed for 10", odds:0.6, fx:[["atk",1]], bad:[["hp",-10]]},
             {label:"lurk", hint:"+25 $CULT", fx:[["cult",25]]} ] },
 { id:"auction", name:"BONKLER AUCTION", icon:"🔨", text:"23 hours on the clock. One Bonkler. The reserve is real.",
   choices:[ {label:"bid 80 $CULT", cost:80, hint:"win a relic draft", fx:[["relic"]]},
             {label:"burn to redeem", need:"relic", hint:"destroy a random relic for 130 $CULT", fx:[["burn",130]]},
             {label:"just watch", hint:"nothing happens", fx:[]} ] },
 { id:"nomeme", name:"THERE IS NO MEME", icon:"💌", text:"A billionaire posts a Milady. \"There is no meme. I love you.\" The floor doubles.",
   choices:[ {label:"take profit", hint:"+90 $CULT", fx:[["cult",90]]},
             {label:"hold", hint:"50%: +200 $CULT · 50%: nothing", odds:0.5, fx:[["cult",200]], bad:[]} ] },
 { id:"exhibit", name:"I LONG FOR NETWORK SPIRITUALITY", icon:"🕯️", text:"A gallery at the edge of the map. The Wired is swallowing the Real.",
   choices:[ {label:"become a lucid conduit", hint:"+8 max HP forever", fx:[["maxhp",8]]},
             {label:"read the manifesto", hint:"reveal the whole map", fx:[["reveal"]]} ] },
 { id:"vibeshift", name:"VIBE SHIFT", icon:"🌀", text:"Overnight, everything that was cool is not. Everything that was not, is.",
   choices:[ {label:"shift with it", need:"relic", hint:"lose a random relic, draft a new one", fx:[["burn",0],["relic"]]},
             {label:"stay indie sleaze", hint:"+1 SPD forever", fx:[["spd",1]]} ] },
 { id:"cancelversary", name:"CANCELVERSARY", icon:"🎂", text:"The community is celebrating the anniversary of the worst day of its life.",
   choices:[ {label:"celebrate", hint:"heal to full", fx:[["hp",999]]},
             {label:"wear it as a badge", hint:"+1 ATK forever, +1 more per boss beaten", fx:[["atkboss"]]} ] },
 { id:"quarterly", name:"REMILIA QUARTERLY", icon:"📖", text:"A dense publication on post-authorship. Plagiarism as praxis.",
   choices:[ {label:"study it", hint:"+1 ATK forever, lose 2 moves", fx:[["atk",1],["moves",-2]]},
             {label:"plagiarize it", hint:"draft a relic, take 6 damage", fx:[["hp",-6],["relic"]]} ] },
 { id:"kagami", name:"KAGAMI ACADEMY", icon:"🏫", text:"Enrollment is open. Tuition is not cheap.",
   choices:[ {label:"enroll · 60 $CULT", cost:60, hint:"+1 SPD and +6 max HP forever", fx:[["spd",1],["maxhp",6]]},
             {label:"skip class", hint:"nothing happens", fx:[]} ] },
 { id:"cheeseworld", name:"CHEESEWORLD", icon:"🧀", text:"Animal yakuza gangs are warring over memetic turf. Cheese is money. Cheese is influence.",
   choices:[ {label:"take the turf", hint:"fight a Shark Kumicho (elite) for his cheese", fx:[["fight","kumicho"]]},
             {label:"pay tribute · 40 $CULT", cost:40, hint:"+2 ATK forever — you go hard now", fx:[["atk",2]]},
             {label:"sell memes on the corner", hint:"60%: +90 $CULT · 40%: shaken down for 12", odds:0.6, fx:[["cult",90]], bad:[["hp",-12]]} ] },
 { id:"ball", name:"THE GRAND REMILIA BALL", icon:"💃", text:"A lavish hall on the Miladycraft server. Admission requires a date. Edating is forbidden.",
   choices:[ {label:"bring your companion", need:"squad", hint:"needs a SQUAD relic · heal to full, draft a rare relic", fx:[["hp",999],["relic",4]]},
             {label:"go alone", hint:"turned away at the door. +30 $CULT of pity", fx:[["cult",30]]},
             {label:"board the blimp", hint:"50%: +150 $CULT · 50%: bombed for 15", odds:0.5, fx:[["cult",150]], bad:[["hp",-15]]} ] },
 { id:"miladycraft", name:"MILADYCRAFT", icon:"⛏️", text:"The minimum viable metaverse. Somewhere near spawn, a seed phrase is buried.",
   choices:[ {label:"mine all night", hint:"+70 $CULT, lose 4 moves", fx:[["cult",70],["moves",-4]]},
             {label:"build a base", hint:"+10 max HP forever", fx:[["maxhp",10]]},
             {label:"ask about the seed phrase", hint:"marks where it is buried on your map", fx:[["seed"]]} ] },
 { id:"webring", name:"RADBRO WEBRING", icon:"🕶️", text:"The brother community, one link over. Radbro is the true nowhere man: a reflection of a reflection, made of everything he isn't.",
   choices:[ {label:"join the webring · 80 $CULT", cost:80, hint:"take the Radbro Webring relic: +1 toward every set you hold", fx:[["give","webring"]]},
             {label:"hang with the radbros", hint:"heal 20 HP, +40 $CULT", fx:[["hp",20],["cult",40]]} ] },
 { id:"station", name:"MILADYSTATION", icon:"🎮", text:"A retro game console with an obscure discography. 1,212 player characters wait on the disc.",
   choices:[ {label:"boot it up", hint:"+8 max HP forever. you are low-poly now", fx:[["maxhp",8],["ps1"]]},
             {label:"save your game · 70 $CULT", cost:70, hint:"take the Memory Card relic: one free reload from death", fx:[["give","memcard"]]},
             {label:"blow on the disc", hint:"50%: +80 $CULT · 50%: nothing", odds:0.5, fx:[["cult",80]], bad:[]} ] },
 { id:"schizopost", name:"SCHIZOPOSTERS", icon:"📡", text:"A face sculpted out of mountains, buried in rabbit-hole lore. The description just says I HATE THE ANTICHRIST, over and over.",
   choices:[ {label:"read all of it", hint:"reveal the whole map, take 5 damage", fx:[["reveal"],["hp",-5]]},
             {label:"post back", hint:"60%: +1 ATK and +1 SPD forever · 40%: lose 3 moves", odds:0.6, fx:[["atk",1],["spd",1]], bad:[["moves",-3]]} ] },
 { id:"ohisee", name:"OH... I SEE", icon:"🪽", text:"˚✧₊⁎ new spring ⁎⁺˳✧༚ Shiro, a princess of Remilia, is drawing. Every one is done by hand. Oh... I've seen.",
   choices:[ {label:"commission a custom · 90 $CULT", cost:90, hint:"take the Oh... I See relic, a hand-drawn 1/1", fx:[["give","custom"]]},
             {label:"watch her draw Eth Chan", hint:"day X of 10k: +1 ATK and +5 max HP forever", fx:[["atk",1],["maxhp",5]]},
             {label:"oh... I see", hint:"reveal the whole map", fx:[["reveal"]]} ] },
 { id:"treasury", name:"THE TREASURY", icon:"🏦", text:"A dev with the keys is acting strange. September is coming.",
   choices:[ {label:"confront the dev", hint:"fight a Rug Dev (elite)", fx:[["fight","rugdev"]]},
             {label:"look away", hint:"lose 30% of your $CULT", fx:[["cultpct",-30]]} ] },
];

/* Achievements are kept forever. Each one adds `relic` to the loot pool of every later run;
   until then that relic cannot drop. The checks live next to the thing they watch in game.js (achieve("id")). */
const ACHIEVEMENTS = [
 {id:"first",       name:"First Blood",            desc:"Win a fight.",                                  relic:"cookie"},
 {id:"seed",        name:"10 ETH",                 desc:"Dig up the seed phrase buried near spawn.",     relic:"blockhead"},
 {id:"exhibit",     name:"Lucid Conduit",          desc:"Visit I Long For Network Spirituality.",        relic:"network_spirituality"},
 {id:"allegations", name:"Posted Through It",      desc:"Defeat the first boss.",                        relic:"tinfoil"},
 {id:"shark",       name:"Turf War",               desc:"Take down a Shark Kumicho.",                    relic:"shark_suit"},
 {id:"fud",         name:"FUD Slayer",             desc:"Kill 3 FUD demons in one run.",                 relic:"vibe_shift"},
 {id:"dodge",       name:"Can't Touch This",       desc:"Dodge 5 attacks in a single fight.",            relic:"milady_pilled"},
 {id:"allin",       name:"Degen",                  desc:"Win an ALL IN shrine flip of 100 $CULT or more.", relic:"game_watch"},
 {id:"rich",        name:"Remilionaire",           desc:"Hold 800 $CULT at once.",                       relic:"remilionaire"},
 {id:"ball",        name:"Had a Date",             desc:"Attend the Grand Remilia Ball with a companion.", relic:"gold_sonic"},
 {id:"synergy",     name:"Full Set",               desc:"Switch on the top tier of any synergy.",        relic:"heart_tattoo"},
 {id:"collector",   name:"Collector",              desc:"Discover 30 different relics.",                 relic:"trucker"},
 {id:"bonkler911",  name:"Never Forget",           desc:"Defeat the second boss.",                       relic:"reserve"},
 {id:"day9",        name:"Cancelversary",          desc:"Survive to day 9.",                             relic:"cancelversary"},
 {id:"win",         name:"Uncancellable",          desc:"Defeat THE CANCEL.",                            relic:"wwe_belt"},
];

const UNLOCKS = [
 {id:"cult1", name:"Seed Funding", cost:200, desc:"Start runs with +100 $CULT."},
 {id:"cult2", name:"Angel Round", cost:400, desc:"Start runs with +250 $CULT.", req:"cult1"},
 {id:"slot1", name:"Extra Pocket", cost:300, desc:"+1 relic slot from the start."},
 {id:"blackmarket", name:"Black Market", cost:350, desc:"Adds 6 cursed relics to the loot pool."},
 {id:"secondchance", name:"Second Chance", cost:500, desc:"Begin every run holding Wartime PFP."},
];
